development:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_dev
  pool: 5
  username: postgres
  password:
 
test:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_tst
  pool: 5
  username: postgres
  password: